### ISSUE TITLE
Import scanpy not found

### ISSUE THREAD

**Issue by cnk113** [AllonKleinLab/cospar#19]
Hello,

When I try to download the latest version from github I get an import error in my conda env, the pypi installation works fine.
```
      Traceback (most recent call last):
        File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/home/chang/cospar/cospar/__init__.py", line 4, in <module>
          from . import datasets, hf, logging, pl, pp, settings, simulate, tl, tmap
        File "/home/chang/cospar/cospar/datasets.py", line 4, in <module>
          from scanpy import read
      ModuleNotFoundError: No module named 'scanpy'
```
Any ideas why this is occuring?

Thanks,
Chang

**Comment by ShouWenWang** [comment]
The last line suggests that you should install scanpy, also some other packages. Try “pip install -r requirements.txt”

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Chang Kim ***@***.***>
Sent: Thursday, September 8, 2022 6:44:36 PM
To: AllonKleinLab/cospar ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AllonKleinLab/cospar] Import scanpy not found (Issue #19)


Hello,

When I try to download the latest version from github I get an import error in my conda env, the pypi installation works fine.

      Traceback (most recent call last):
        File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/chang/miniconda3/envs/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nrq06iwn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/home/chang/cospar/cospar/__init__.py", line 4, in <module>
          from . import datasets, hf, logging, pl, pp, settings, simulate, tl, tmap
        File "/home/chang/cospar/cospar/datasets.py", line 4, in <module>
          from scanpy import read
      ModuleNotFoundError: No module named 'scanpy'


Any ideas why this is occuring?

Thanks,
Chang

**Comment by cnk113** [comment]
So it is installed, I even tried it with a new conda venv and it gives the same error.

**Comment by ShouWenWang** [comment]
Try this 
```bash
conda create -n CoSpar_envs python=3.8
conda activate CoSpar_envs
pip install -r  requirements.txt
pip install pot scanpy wot
pip install --user ipykernel
python -m ipykernel install --user --name=CoSpar_envs
```

**Comment by ShouWenWang** [comment]
This should be run at the root directory of cospar folder

**Comment by cnk113** [comment]
Hmm it still doesn't work with that environment. I even tried to install it locally on my macbook, but I get the same exact error...

**Comment by ShouWenWang** [comment]
Maybe, you can try to install with `pip install cospar` into a given environment. Then, uninstall cospar with `pip uninstall cospar`, and then go to the CoSpar directory that you clone from here, and run `python setup.py install` or `python setup.py develop`.
