### ISSUE TITLE
Error in running CoSpar on the Lung differentiation dataset

### ISSUE THREAD

**Issue by bhyu0217** [AllonKleinLab/cospar#26]
Hi,
This method is very fascinating, and I am trying to reproduce the tutorial results with the Lung differentiation dataset.
I created a new conda environment and installed all the packages on the conda environment.

When I executed these two commands with CoSpar, I got these errors:

```
>>> cs.tl.fate_coupling(
    adata_orig,
    source="X_clone",
    selected_fates=["iAEC2", "PNEC", "Gut", "NLE", "Endoderm"],
)

normalize by X_clone
each selected cluster has a unique time point. Normalize per time point
/home/bhyu/anaconda3/envs/cospar/lib/python3.9/site-packages/cospar/tool/_utils.py:75: RuntimeWarning: invalid value encountered in double_scalars
  X[j, k] = X[j, k] / (diag_temp[j] * diag_temp[k])
Results saved as dictionary at adata.uns['fate_coupling_X_clone']

>>> cs.pl.fate_coupling(adata_orig, source="X_clone")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bhyu/anaconda3/envs/cospar/lib/python3.9/site-packages/cospar/plotting/_map.py", line 87, in fate_coupling
    ax = pl_util.heatmap(
  File "/home/bhyu/anaconda3/envs/cospar/lib/python3.9/site-packages/cospar/plotting/_utils.py", line 353, in heatmap
    Z = hierarchy.ward(data_matrix + pseudo_count)
  File "/home/bhyu/anaconda3/envs/cospar/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 834, in ward
    return linkage(y, method='ward', metric='euclidean')
  File "/home/bhyu/anaconda3/envs/cospar/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 1065, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.
```

Could you please help me with this issue?
Thank you.

Best,
Bohyeon

**Comment by ShouWenWang** [comment]
Hi, Bohyeon
       This erroneous behavior is due to the presence of a cluster ('Endoderm') that has no clones in it. I fixed it by removing any clusters without clones in the coupling calculation. If you git clone the lastest version of CoSpar (with git tag: [eb3745e](https://github.com/AllonKleinLab/cospar/commit/eb3745e3c30d994fcf911cd00a950ea722246670)), this problem will be resolved!

**Comment by bhyu0217** [comment]
Hi, @ShouWenWang 
Thank you so much for your immense help!!!
Cospar is working well now.
